# Generated by Django 4.2.4 on 2024-10-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_alter_site_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
