# Generated by Django 4.2.4 on 2024-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_site_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kh', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'LeaveType',
            },
        ),
    ]
