# Generated by Django 4.2.4 on 2024-10-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_department_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('email_approver_l1', models.EmailField(blank=True, max_length=254)),
                ('email_approver_l2', models.EmailField(blank=True, max_length=254)),
                ('email_approver_l3', models.EmailField(blank=True, max_length=254)),
                ('approver_email', models.EmailField(max_length=254)),
                ('aknowledge_by', models.TextField(help_text='Multiple emails separated by semicolon (;)')),
                ('status', models.BooleanField(default=True)),
                ('allow_date', models.IntegerField(help_text='Allowed days of leave')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.section')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.site')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
