# Generated by Django 4.2.4 on 2024-10-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0006_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
